-- Обновление структуры таблицы bets
ALTER TABLE bets ADD COLUMN IF NOT EXISTS lvl INT DEFAULT 1;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS fire INT DEFAULT 0;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS finish INT DEFAULT 0;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS result DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS status INT DEFAULT 2;

-- Проверим структуру таблицы
DESCRIBE bets;